/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, useTexture, useVideoTexture } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import Avatar from "./Avatar";
import { gsap } from "gsap";

export default function Desk(props) {
	const { nodes, materials } = useGLTF("/models/Desk.glb");
	const vidTexture = useVideoTexture("/videos/videoTextture.mp4");
	const groupRef = useRef();
	const screenRef = useRef();
	vidTexture.flipY = false;

	useFrame((state, delta) => {
		const cursorX = state.pointer.x / state.viewport.width;
		const cursorY = state.pointer.y / state.viewport.height;

		gsap.to(groupRef.current.position, {
			x: cursorX * 0.5,
			y: cursorY * 0.5,
			duration: 0.5,
		});
	});

	return (
		<group
			ref={groupRef}
			{...props}
			dispose={null}>
			<group name='Scene'>
				<mesh
					name='Table'
					castShadow
					receiveShadow
					geometry={nodes.Table.geometry}
					material={materials["Material.001"]}
					position={[0, 0.742, 0]}
					rotation={[Math.PI, 0, Math.PI]}
					scale={0.273}
				/>
				<mesh
					name='Pc'
					castShadow
					receiveShadow
					geometry={nodes.Pc.geometry}
					material={materials.Main}
					position={[0, 0.742, 0]}
					rotation={[Math.PI, 0, Math.PI]}
					scale={0.273}>
					<group name='GPU1'>
						<mesh
							name='Plane003'
							castShadow
							receiveShadow
							geometry={nodes.Plane003.geometry}
							material={materials.MotherBoard}
						/>
						<mesh
							name='Plane003_1'
							castShadow
							receiveShadow
							geometry={nodes.Plane003_1.geometry}
							material={materials.RGB}
						/>
					</group>
					<group name='GPU2'>
						<mesh
							name='Plane009'
							castShadow
							receiveShadow
							geometry={nodes.Plane009.geometry}
							material={materials.MotherBoard}
						/>
						<mesh
							name='Plane009_1'
							castShadow
							receiveShadow
							geometry={nodes.Plane009_1.geometry}
							material={materials.RGB}
						/>
					</group>
					<mesh
						name='Motherboard'
						castShadow
						receiveShadow
						geometry={nodes.Motherboard.geometry}
						material={materials.MotherBoard}
					/>
					<mesh
						name='PowerSupply'
						castShadow
						receiveShadow
						geometry={nodes.PowerSupply.geometry}
						material={nodes.PowerSupply.material}
					/>
				</mesh>
				<mesh
					name='Monitor'
					castShadow
					receiveShadow
					geometry={nodes.Monitor.geometry}
					material={materials.Main}
					position={[0, 0.742, 0]}
					rotation={[Math.PI, 0, Math.PI]}
					scale={0.273}>
					<mesh
						ref={screenRef}
						name='Screen'
						castShadow
						receiveShadow
						geometry={nodes.Screen.geometry}
						material={materials.Material}
					/>
				</mesh>
				<mesh
					name='Keyboard'
					castShadow
					receiveShadow
					geometry={nodes.Keyboard.geometry}
					material={materials["Base.001"]}
					position={[0, 0.73, 0.04]}
					rotation={[Math.PI, 0, Math.PI]}
					scale={0.273}>
					<mesh
						name='KeyCaps'
						castShadow
						receiveShadow
						geometry={nodes.KeyCaps.geometry}
						material={nodes.KeyCaps.material}
					/>
				</mesh>
				<mesh
					name='MouseThermaltakeBlack'
					castShadow
					receiveShadow
					geometry={nodes.MouseThermaltakeBlack.geometry}
					material={materials.SimpleBake_Placeholder}
					position={[0, 0.742, 0]}
					rotation={[Math.PI, 0, Math.PI]}
					scale={0.273}
				/>
				<mesh
					name='office_chair_013'
					castShadow
					receiveShadow
					geometry={nodes.office_chair_013.geometry}
					material={materials.Base}
					position={[0, 0.79, 0]}
					rotation={[Math.PI, 0, Math.PI]}
					scale={0.273}
				/>
				<mesh
					name='PcCover'
					castShadow
					receiveShadow
					geometry={nodes.PcCover.geometry}
					material={materials.GlassPanel}
					position={[0, 0.742, 0]}
					rotation={[Math.PI, 0, Math.PI]}
					scale={0.273}
				/>
				<group
					name='Empty'
					position={[0.453, 0.28, 1.052]}
					rotation={[Math.PI, 0, Math.PI]}
					scale={1.3}>
					<Avatar />
				</group>
			</group>
		</group>
	);
}

useGLTF.preload("/models/Desk.glb");
