/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function LandingRoom(props) {
	const { nodes, materials } = useGLTF("/models/LandingRoom.glb");
	return (
		<group
			{...props}
			dispose={null}>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.IphoneScreen.geometry}
				material={materials.Screen}
				position={[0.871, 3.3, -1.705]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.RightMonitorScreen.geometry}
				material={materials["Material.001"]}
				position={[-0.363, 3.922, -3.258]}
				rotation={[Math.PI / 2, 0, 0]}
			/>
			<group position={[2.425, 2.919, -2.392]}>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Plane007.geometry}
					material={materials["tv stanb"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Plane007_1.geometry}
					material={materials["Material.002"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Plane007_2.geometry}
					material={materials.Keyboard}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Plane007_3.geometry}
					material={materials.Green}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Plane007_4.geometry}
					material={materials.Red}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Plane007_5.geometry}
					material={materials.Yellow}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Plane007_6.geometry}
					material={materials.Blue}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Plane007_7.geometry}
					material={materials.white}
				/>
			</group>
			<group
				position={[-0.363, 3.922, -3.265]}
				rotation={[Math.PI / 2, 0, 0]}>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Plane009.geometry}
					material={materials.TVFrame}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Plane009_1.geometry}
					material={materials["tv stanb"]}
				/>
			</group>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.PenHolder.geometry}
				material={materials.Keycaps}
				position={[0.922, 3.252, -3.042]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Phone.geometry}
				material={materials.Iphone}
				position={[0.871, 3.291, -1.705]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Airpod.geometry}
				material={nodes.Airpod.material}
				position={[-0.875, 3.261, -3.045]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Text.geometry}
				material={nodes.Text.material}
				position={[-11.578, 0.176, -3.947]}
				rotation={[Math.PI / 2, 0, 0.869]}
			/>
			<group
				position={[-0.896, 1.412, -0.021]}
				rotation={[0, -0.524, 0]}>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Circle003.geometry}
					material={materials.Wall}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Circle003_1.geometry}
					material={materials.Wheels}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Circle003_2.geometry}
					material={materials.TableLegs}
				/>
			</group>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Wall_Baked.geometry}
				material={materials.MergedBake_Baked}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Table_Baked.geometry}
				material={materials.MergedBake_Baked}
				position={[-1.203, 3.175, -2.289]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Shelf_Baked.geometry}
				material={materials.MergedBake_Baked}
				position={[-0.902, 5.925, -3.423]}
				rotation={[Math.PI / 2, 0, 0]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Window_Baked.geometry}
				material={materials.MergedBake_Baked}
				position={[4.751, 4.101, 1.624]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Floor_Baked.geometry}
				material={materials.MergedBake_Baked}
				position={[-3.769, 0.577, 3.711]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Book002_Baked.geometry}
				material={materials.MergedBake_Baked}
				position={[2.301, 5.278, -2.54]}
				rotation={[0, 0, -0.343]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Keyboard_Baked.geometry}
				material={materials.MergedBake_Baked}
				position={[-0.901, 3.264, -1.674]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Circle_Baked.geometry}
				material={materials.MergedBake_Baked}
				position={[-0.862, 0.937, -0.195]}
				rotation={[0, Math.PI / 2, 0]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Briefcase_Baked.geometry}
				material={materials.MergedBake_Baked}
				position={[-8.202, 1.421, -2.703]}
				rotation={[0, 0.838, -1.772]}
				scale={0.64}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Drawer003_Baked.geometry}
				material={materials.MergedBake_Baked}
				position={[2.382, 0.954, -2.398]}
			/>
		</group>
	);
}

useGLTF.preload("/models/LandingRoom.glb");
